title: Athena Jekyll Theme
description: A simple and elegant theme for Jekyll and GitHub Pages.
social_link: twitter
social_username: broccolini
github_repo: athena
github_username: broccolini
theme_color: light
remote_theme: internet-de-france/athena
remote_theme_layouts:
  - default
  - page
  - post
  - home
  - category_index
baseurl: /crapulous_stylist
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
